# Generated by Django 5.2.14 on 2026-05-19 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('display_currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('INR', 'Indian Rupee'), ('GBP', 'British Pound'), ('CHF', 'Swiss Franc')], default='EUR', max_length=3)),
                ('last_sync_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'app settings',
                'db_table': 'settings',
            },
        ),
    ]
