"""Framework-independent finance logic (no Django imports)."""

from finance.fifo import (
    FifoCostBasisMetrics,
    build_split_adjusted_lot_snapshots,
    calculate_fifo_cost_basis_metrics,
)
from finance.oversell import detect_oversell
from finance.splits import apply_stock_split_adjustments
from finance.comparison import (
    AlignedReturnPoint,
    BenchmarkSummary,
    active_return,
    align_multi_subject_returns,
    align_return_series,
    alpha,
    benchmark_summary,
    beta,
    correlation,
    information_ratio,
    normalized_cumulative_return_series,
    tracking_error,
    treynor_ratio,
)
from finance.drawdowns import (
    DrawdownPoint,
    WorstDrawdownPeriod,
    calmar_ratio,
    drawdown_series,
    longest_drawdown_days,
    max_drawdown,
    worst_drawdown_periods,
)
from finance.performance_stats import (
    PeriodSummary,
    average_return,
    best_return,
    cagr,
    cumulative_return,
    period_summary,
    win_rate,
    worst_return,
)
from finance.risk_metrics import (
    annualized_volatility,
    downside_deviation,
    sharpe_ratio,
    sortino_ratio,
)
from finance.returns import (
    DailyReturnPoint,
    PeriodReturnPoint,
    ValuePoint,
    chain_returns,
    compound_return,
    daily_returns_from_twror_series,
    daily_returns_from_values,
    period_return,
    resample_monthly_returns,
    resample_yearly_returns,
)
from finance.twror import TwrorPoint, compute_twror_series
from finance.types import Transaction, TransactionType
from finance.xirr import build_xirr_cashflows, calculate_xirr

__all__ = [
    "FifoCostBasisMetrics",
    "Transaction",
    "TransactionType",
    "TwrorPoint",
    "AlignedReturnPoint",
    "BenchmarkSummary",
    "DailyReturnPoint",
    "DrawdownPoint",
    "WorstDrawdownPeriod",
    "PeriodReturnPoint",
    "PeriodSummary",
    "ValuePoint",
    "active_return",
    "align_multi_subject_returns",
    "align_return_series",
    "alpha",
    "annualized_volatility",
    "average_return",
    "benchmark_summary",
    "beta",
    "apply_stock_split_adjustments",
    "best_return",
    "calmar_ratio",
    "cagr",
    "cumulative_return",
    "downside_deviation",
    "drawdown_series",
    "information_ratio",
    "build_split_adjusted_lot_snapshots",
    "detect_oversell",
    "build_xirr_cashflows",
    "calculate_fifo_cost_basis_metrics",
    "calculate_xirr",
    "chain_returns",
    "compound_return",
    "compute_twror_series",
    "correlation",
    "daily_returns_from_twror_series",
    "daily_returns_from_values",
    "longest_drawdown_days",
    "max_drawdown",
    "normalized_cumulative_return_series",
    "period_return",
    "period_summary",
    "resample_monthly_returns",
    "resample_yearly_returns",
    "sharpe_ratio",
    "sortino_ratio",
    "tracking_error",
    "treynor_ratio",
    "win_rate",
    "worst_return",
    "worst_drawdown_periods",
]
