# Generated by Django 5.2.14 on 2026-06-13 22:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0004_alter_portfolio_cash_aware_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('institution_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=128)),
                ('currency', models.CharField(max_length=3)),
                ('opening_balance', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('current_balance', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('include_in_portfolio_value', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='FixedDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('deposit_account_number', models.CharField(max_length=128)),
                ('principal_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('interest_rate_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('interest_payout_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half yearly'), ('ANNUALLY', 'Annually'), ('COMPOUNDED', 'Compounded')], max_length=16)),
                ('investment_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('nominee_name', models.CharField(blank=True, default='', max_length=255)),
                ('comment', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MATURED', 'Matured'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_deposits', to='debt.bankaccount')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_deposits', to='portfolios.portfolio')),
                ('renewal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='debt.fixeddeposit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fixed_deposits',
            },
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['user', 'is_active'], name='bank_accoun_user_id_224f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['user', 'name'], name='bank_accoun_user_id_f364b4_idx'),
        ),
        migrations.AddIndex(
            model_name='fixeddeposit',
            index=models.Index(fields=['user', 'is_active'], name='fixed_depos_user_id_53bd77_idx'),
        ),
        migrations.AddIndex(
            model_name='fixeddeposit',
            index=models.Index(fields=['portfolio', 'is_active'], name='fixed_depos_portfol_3b93db_idx'),
        ),
        migrations.AddIndex(
            model_name='fixeddeposit',
            index=models.Index(fields=['portfolio', 'status'], name='fixed_depos_portfol_6b33a9_idx'),
        ),
        migrations.AddIndex(
            model_name='fixeddeposit',
            index=models.Index(fields=['bank_account'], name='fixed_depos_bank_ac_a34b5c_idx'),
        ),
    ]
