# Generated by Django 5.2.14 on 2026-06-13 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0001_initial'),
        ('portfolios', '0004_alter_portfolio_cash_aware_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('OPENING_BALANCE', 'Opening balance'), ('MANUAL_DEPOSIT', 'Manual deposit'), ('MANUAL_WITHDRAWAL', 'Manual withdrawal'), ('TRANSFER_IN', 'Transfer in'), ('TRANSFER_OUT', 'Transfer out'), ('ADJUSTMENT', 'Adjustment')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('direction', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=8)),
                ('currency', models.CharField(max_length=3)),
                ('movement_date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('SYSTEM', 'System')], default='MANUAL', max_length=16)),
                ('is_reversal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='debt.bankaccount')),
                ('linked_fixed_deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='debt.fixeddeposit')),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_cash_movements', to='portfolios.portfolio')),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_rows', to='debt.cashmovement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cash_movements',
                'indexes': [models.Index(fields=['user', 'bank_account'], name='cash_moveme_user_id_380573_idx'), models.Index(fields=['bank_account', 'movement_date'], name='cash_moveme_bank_ac_1781fe_idx'), models.Index(fields=['bank_account', 'movement_type'], name='cash_moveme_bank_ac_2cc4e0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='cash_movements_amount_positive')],
            },
        ),
    ]
