# Generated by Django 5.2.14 on 2026-06-14 08:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0002_cash_movement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovement',
            name='movement_type',
            field=models.CharField(choices=[('OPENING_BALANCE', 'Opening balance'), ('MANUAL_DEPOSIT', 'Manual deposit'), ('MANUAL_WITHDRAWAL', 'Manual withdrawal'), ('FD_OPENING', 'Fixed deposit opening'), ('FD_INTEREST', 'Fixed deposit interest'), ('TRANSFER_IN', 'Transfer in'), ('TRANSFER_OUT', 'Transfer out'), ('ADJUSTMENT', 'Adjustment')], max_length=32),
        ),
        migrations.CreateModel(
            name='FixedDepositInterestPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('gross_interest', models.DecimalField(decimal_places=4, max_digits=18)),
                ('tax_withheld', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('net_interest', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_deposit_interest_payments', to='debt.bankaccount')),
                ('cash_movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_deposit_interest_payment', to='debt.cashmovement')),
                ('fixed_deposit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interest_payments', to='debt.fixeddeposit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_deposit_interest_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fixed_deposit_interest_payments',
                'indexes': [models.Index(fields=['user', 'fixed_deposit'], name='fixed_depos_user_id_0aadaf_idx'), models.Index(fields=['fixed_deposit', 'payment_date'], name='fixed_depos_fixed_d_7c6aeb_idx'), models.Index(fields=['bank_account', 'payment_date'], name='fixed_depos_bank_ac_4bb407_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('gross_interest__gt', 0)), name='fd_interest_payments_gross_positive'), models.CheckConstraint(condition=models.Q(('tax_withheld__gte', 0)), name='fd_interest_payments_tax_non_negative'), models.CheckConstraint(condition=models.Q(('net_interest__gte', 0)), name='fd_interest_payments_net_non_negative')],
            },
        ),
    ]
