# Generated by Django 5.2.14 on 2026-06-14 09:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0003_fixed_deposit_interest_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovement',
            name='movement_type',
            field=models.CharField(choices=[('OPENING_BALANCE', 'Opening balance'), ('MANUAL_DEPOSIT', 'Manual deposit'), ('MANUAL_WITHDRAWAL', 'Manual withdrawal'), ('FD_OPENING', 'Fixed deposit opening'), ('FD_INTEREST', 'Fixed deposit interest'), ('FD_MATURITY_PRINCIPAL', 'Fixed deposit maturity principal'), ('FD_MATURITY_INTEREST', 'Fixed deposit maturity interest'), ('FD_CLOSURE_PRINCIPAL', 'Fixed deposit closure principal'), ('FD_CLOSURE_INTEREST', 'Fixed deposit closure interest'), ('TRANSFER_IN', 'Transfer in'), ('TRANSFER_OUT', 'Transfer out'), ('ADJUSTMENT', 'Adjustment')], max_length=32),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('MATURED', 'Matured'), ('MATURED_SETTLED', 'Matured (settled)'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=16),
        ),
        migrations.CreateModel(
            name='FixedDepositSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_type', models.CharField(choices=[('MATURITY', 'Maturity'), ('CLOSURE', 'Closure')], max_length=16)),
                ('settlement_date', models.DateField()),
                ('principal_returned', models.DecimalField(decimal_places=4, max_digits=18)),
                ('gross_interest', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('tax_withheld', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('net_interest', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('total_net_proceeds', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_deposit_settlements', to='debt.bankaccount')),
                ('fixed_deposit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='debt.fixeddeposit')),
                ('interest_cash_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_deposit_settlement_interest', to='debt.cashmovement')),
                ('principal_cash_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_deposit_settlement_principal', to='debt.cashmovement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_deposit_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fixed_deposit_settlements',
                'indexes': [models.Index(fields=['user', 'fixed_deposit'], name='fixed_depos_user_id_4ae0e7_idx'), models.Index(fields=['bank_account', 'settlement_date'], name='fixed_depos_bank_ac_89f30f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('principal_returned__gte', 0)), name='fd_settlements_principal_non_negative'), models.CheckConstraint(condition=models.Q(('gross_interest__gte', 0)), name='fd_settlements_gross_non_negative'), models.CheckConstraint(condition=models.Q(('tax_withheld__gte', 0)), name='fd_settlements_tax_non_negative'), models.CheckConstraint(condition=models.Q(('net_interest__gte', 0)), name='fd_settlements_net_non_negative'), models.CheckConstraint(condition=models.Q(('total_net_proceeds__gt', 0)), name='fd_settlements_total_proceeds_positive')],
            },
        ),
    ]
