# Generated by Django 5.2.14 on 2026-06-14 09:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0004_fixed_deposit_settlement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedDepositRenewalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_date', models.DateField()),
                ('old_principal', models.DecimalField(decimal_places=4, max_digits=18)),
                ('direct_reinvest_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('cash_payout_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('gross_interest', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('tax_withheld', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('net_interest', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('total_maturity_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_fixed_deposit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewal_as_new', to='debt.fixeddeposit')),
                ('old_fixed_deposit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewal_as_old', to='debt.fixeddeposit')),
                ('settlement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='renewal_group', to='debt.fixeddepositsettlement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_deposit_renewal_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fixed_deposit_renewal_groups',
                'indexes': [models.Index(fields=['user', 'old_fixed_deposit'], name='fixed_depos_user_id_22e773_idx'), models.Index(fields=['user', 'new_fixed_deposit'], name='fixed_depos_user_id_513679_idx'), models.Index(fields=['renewal_date'], name='fixed_depos_renewal_c3f35d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('old_principal__gt', 0)), name='fd_renewal_groups_old_principal_positive'), models.CheckConstraint(condition=models.Q(('direct_reinvest_amount__gt', 0)), name='fd_renewal_groups_direct_reinvest_positive'), models.CheckConstraint(condition=models.Q(('cash_payout_amount__gte', 0)), name='fd_renewal_groups_cash_payout_non_negative'), models.CheckConstraint(condition=models.Q(('gross_interest__gte', 0)), name='fd_renewal_groups_gross_non_negative'), models.CheckConstraint(condition=models.Q(('tax_withheld__gte', 0)), name='fd_renewal_groups_tax_non_negative'), models.CheckConstraint(condition=models.Q(('net_interest__gte', 0)), name='fd_renewal_groups_net_non_negative'), models.CheckConstraint(condition=models.Q(('total_maturity_value__gt', 0)), name='fd_renewal_groups_total_maturity_positive')],
            },
        ),
    ]
