# Generated by Django 5.2.14 on 2026-06-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0007_reversal_framework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovement',
            name='movement_type',
            field=models.CharField(choices=[('OPENING_BALANCE', 'Opening balance'), ('MANUAL_DEPOSIT', 'Manual deposit'), ('MANUAL_WITHDRAWAL', 'Manual withdrawal'), ('FD_OPENING', 'Fixed deposit opening'), ('FD_OPENING_REVERSAL', 'Fixed deposit opening reversal'), ('FD_INTEREST', 'Fixed deposit interest'), ('FD_INTEREST_REVERSAL', 'Fixed deposit interest reversal'), ('REVERSAL', 'Reversal'), ('FD_MATURITY_PRINCIPAL', 'Fixed deposit maturity principal'), ('FD_MATURITY_INTEREST', 'Fixed deposit maturity interest'), ('FD_CLOSURE_PRINCIPAL', 'Fixed deposit closure principal'), ('FD_CLOSURE_INTEREST', 'Fixed deposit closure interest'), ('TRANSFER_IN', 'Transfer in'), ('TRANSFER_OUT', 'Transfer out'), ('ADJUSTMENT', 'Adjustment')], max_length=32),
        ),
    ]
