# Generated by Django 5.2.14 on 2026-06-26 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("debt", "0009_bankaccount_portfolio"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="bankaccount",
            new_name="bank_accoun_user_id_b3da01_idx",
            old_name="bank_accounts_user_port_idx",
        ),
    ]
