# Generated by Django 5.2.14 on 2026-05-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkIndexConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('source', models.CharField(default='yfinance', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'benchmark_index_config',
                'indexes': [models.Index(fields=['enabled'], name='benchmark_i_enabled_dbb0b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_symbol', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('close_price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('source', models.CharField(default='yfinance', max_length=64)),
                ('asset_type', models.CharField(choices=[('STOCK', 'Stock'), ('INDEX', 'Index'), ('ETF', 'ETF'), ('FX', 'FX')], default='STOCK', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'historical_prices',
                'indexes': [models.Index(fields=['asset_symbol', 'date'], name='historical__asset_s_710d27_idx'), models.Index(fields=['asset_type', 'asset_symbol'], name='historical__asset_t_fdcaa2_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset_symbol', 'date'), name='uq_historical_prices_asset_date')],
            },
        ),
    ]
