# Generated by Django 5.2.14 on 2026-05-26 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprice',
            name='asset_type',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('INDEX', 'Index'), ('ETF', 'ETF'), ('FX', 'FX'), ('MUTUAL_FUND', 'Mutual fund')], default='STOCK', max_length=16),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('STOCK', 'Stock'), ('INDEX', 'Index'), ('ETF', 'ETF'), ('FX', 'FX'), ('MUTUAL_FUND', 'Mutual fund')], max_length=16)),
                ('symbol', models.CharField(max_length=32)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('provider_symbol', models.CharField(blank=True, default='', max_length=64)),
                ('primary_asset_class', models.CharField(blank=True, choices=[('EQUITY', 'Equity'), ('DEBT', 'Debt'), ('HYBRID', 'Hybrid'), ('LIQUID', 'Liquid'), ('COMMODITY', 'Commodity'), ('OTHER', 'Other')], max_length=16, null=True)),
                ('region', models.CharField(blank=True, default='', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assets',
                'indexes': [models.Index(fields=['asset_type', 'symbol'], name='assets_asset_t_c78eef_idx'), models.Index(fields=['is_active'], name='assets_is_acti_0f03da_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset_type', 'symbol'), name='uq_assets_type_symbol')],
            },
        ),
        migrations.AddField(
            model_name='historicalprice',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_prices', to='market_data.asset'),
        ),
        migrations.CreateModel(
            name='MutualFundProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_code', models.CharField(max_length=32, unique=True)),
                ('scheme_name', models.CharField(max_length=512)),
                ('fund_house', models.CharField(blank=True, default='', max_length=255)),
                ('scheme_type', models.CharField(blank=True, default='', max_length=128)),
                ('scheme_category', models.CharField(blank=True, default='', max_length=255)),
                ('isin_growth', models.CharField(blank=True, default='', max_length=12)),
                ('isin_reinvestment', models.CharField(blank=True, default='', max_length=12)),
                ('direct_or_regular', models.CharField(blank=True, default='', max_length=16)),
                ('growth_or_idcw', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mutual_fund_profile', to='market_data.asset')),
            ],
            options={
                'db_table': 'mutual_fund_profiles',
                'indexes': [models.Index(fields=['scheme_name'], name='mutual_fund_scheme__4cb20b_idx'), models.Index(fields=['fund_house'], name='mutual_fund_fund_ho_8229f2_idx')],
            },
        ),
    ]
