# Generated by Django 5.2.14 on 2026-05-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_mutual_fund_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='primary_asset_class',
            field=models.CharField(blank=True, choices=[('EQUITY', 'Equity'), ('DEBT', 'Debt'), ('HYBRID', 'Hybrid'), ('LIQUID', 'Liquid'), ('COMMODITY', 'Commodity'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], max_length=16, null=True),
        ),
    ]
