# Generated by Django 5.2.14 on 2026-05-19 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_symbol', models.CharField(db_index=True, max_length=32)),
                ('date', models.DateField(db_index=True)),
                ('type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIVIDEND', 'Dividend'), ('STOCK_SPLIT', 'Stock split')], max_length=16)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('price_per_share', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('fees', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('split_from', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('split_to', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='portfolios.portfolio')),
            ],
            options={
                'db_table': 'transactions',
                'indexes': [models.Index(fields=['portfolio', 'date'], name='transaction_portfol_e69164_idx'), models.Index(fields=['asset_symbol', 'date'], name='transaction_asset_s_2633a7_idx'), models.Index(fields=['portfolio', 'asset_symbol'], name='transaction_portfol_625781_idx')],
            },
        ),
    ]
