# Generated by Django 5.2.14 on 2026-05-26 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_mutual_fund_schema'),
        ('portfolios', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_number', models.CharField(max_length=64)),
                ('folio_alias', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folios', to='market_data.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folios', to='portfolios.portfolio')),
            ],
            options={
                'db_table': 'folios',
            },
        ),
        migrations.CreateModel(
            name='MutualFundTransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_date', models.DateField()),
                ('nav_date', models.DateField()),
                ('nav', models.DecimalField(decimal_places=6, max_digits=18)),
                ('units_allotted', models.DecimalField(decimal_places=8, max_digits=18)),
                ('paid_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('market_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('nav_verification_status', models.CharField(choices=[('NOT_VERIFIED', 'Not verified'), ('OK', 'OK'), ('WARNING', 'Warning'), ('UNCHECKED', 'Unchecked')], default='NOT_VERIFIED', max_length=16)),
                ('nav_verification_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mutual_fund_transactions', to='transactions.folio')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mutual_fund_detail', to='transactions.transaction')),
            ],
            options={
                'db_table': 'mutual_fund_transaction_details',
            },
        ),
        migrations.AddIndex(
            model_name='folio',
            index=models.Index(fields=['portfolio', 'asset'], name='folios_portfol_b94722_idx'),
        ),
        migrations.AddIndex(
            model_name='folio',
            index=models.Index(fields=['is_active'], name='folios_is_acti_093bef_idx'),
        ),
        migrations.AddConstraint(
            model_name='folio',
            constraint=models.UniqueConstraint(fields=('portfolio', 'asset', 'folio_number'), name='uq_folio_portfolio_asset_number'),
        ),
        migrations.AddIndex(
            model_name='mutualfundtransactiondetail',
            index=models.Index(fields=['nav_date'], name='mutual_fund_nav_dat_1319a3_idx'),
        ),
        migrations.AddIndex(
            model_name='mutualfundtransactiondetail',
            index=models.Index(fields=['investment_date'], name='mutual_fund_investm_1d9f49_idx'),
        ),
    ]
