# Generated by Django 5.2.14 on 2026-05-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_mutual_fund_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutualfundtransactiondetail',
            name='nav_verification_status',
            field=models.CharField(choices=[('NOT_VERIFIED', 'Not verified'), ('VERIFIED', 'Verified'), ('NAV_MISSING', 'NAV missing'), ('NAV_MISMATCH', 'NAV mismatch'), ('VALUE_MISMATCH', 'Value mismatch'), ('WARNING_ACCEPTED', 'Warning accepted'), ('OK', 'OK'), ('WARNING', 'Warning'), ('UNCHECKED', 'Unchecked')], default='NOT_VERIFIED', max_length=16),
        ),
    ]
