# Generated by Django 5.2.14 on 2026-05-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FXRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('source', models.CharField(default='yfinance', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fx_rates',
                'indexes': [models.Index(fields=['from_currency', 'to_currency', 'date'], name='fx_rates_from_cu_1f3b14_idx'), models.Index(fields=['date'], name='fx_rates_date_c7fe1e_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_currency', 'to_currency', 'date'), name='uq_fx_rates_pair_date')],
            },
        ),
    ]
