# Generated by Django 5.2.14 on 2026-06-04 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0003_portfolio_cash_aware_enabled'),
        ('transactions', '0003_alter_mutualfundtransactiondetail_nav_verification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransferGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('source_currency', models.CharField(max_length=3)),
                ('target_currency', models.CharField(max_length=3)),
                ('source_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('target_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('user_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('fees', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('fee_currency', models.CharField(blank=True, default='', max_length=3)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_transfers_out', to='portfolios.portfolio')),
                ('target_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_transfers_in', to='portfolios.portfolio')),
            ],
            options={
                'db_table': 'cash_transfer_groups',
            },
        ),
        migrations.CreateModel(
            name='CashLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('currency', models.CharField(max_length=3)),
                ('entry_type', models.CharField(choices=[('CASH_DEPOSIT', 'Cash deposit'), ('CASH_WITHDRAWAL', 'Cash withdrawal'), ('BUY_SETTLEMENT', 'Buy settlement'), ('SELL_SETTLEMENT', 'Sell settlement'), ('DIVIDEND_CASH', 'Dividend (cash)'), ('INTEREST', 'Interest'), ('FEE', 'Fee'), ('TAX', 'Tax'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER_OUT', 'Transfer out'), ('TRANSFER_IN', 'Transfer in'), ('FX_CONVERSION_OUT', 'FX conversion out'), ('FX_CONVERSION_IN', 'FX conversion in')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('source_of_funds', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_ledger_entries', to='transactions.transaction')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_ledger_entries', to='portfolios.portfolio')),
                ('transfer_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='cash.cashtransfergroup')),
            ],
            options={
                'db_table': 'cash_ledger_entries',
            },
        ),
        migrations.AddIndex(
            model_name='cashtransfergroup',
            index=models.Index(fields=['date'], name='cash_transf_date_a5dbc4_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransfergroup',
            index=models.Index(fields=['source_portfolio', 'date'], name='cash_transf_source__bd9e06_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransfergroup',
            index=models.Index(fields=['target_portfolio', 'date'], name='cash_transf_target__2c7587_idx'),
        ),
        migrations.AddIndex(
            model_name='cashledgerentry',
            index=models.Index(fields=['portfolio', 'currency', 'date'], name='cash_ledger_portfol_dce228_idx'),
        ),
        migrations.AddIndex(
            model_name='cashledgerentry',
            index=models.Index(fields=['portfolio', 'date'], name='cash_ledger_portfol_d561bc_idx'),
        ),
        migrations.AddIndex(
            model_name='cashledgerentry',
            index=models.Index(fields=['linked_transaction'], name='cash_ledger_linked__986a0a_idx'),
        ),
    ]
