# Generated by Django 5.2.14 on 2026-05-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_currency', models.CharField(default='EUR', max_length=3)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'portfolios',
                'indexes': [models.Index(fields=['is_active'], name='portfolios_is_acti_54a725_idx'), models.Index(fields=['name'], name='portfolios_name_61664a_idx'), models.Index(fields=['is_default'], name='portfolios_is_defa_81001c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='uniq_portfolios_default')],
            },
        ),
    ]
