# Generated by Django 5.2.14 on 2026-06-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_user_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='cash_aware_enabled',
            field=models.BooleanField(default=False, help_text='When true, cash ledger rules apply (later phases). False keeps legacy BUY/SELL external-flow behavior.'),
        ),
    ]
