# Generated by Django 5.2.14 on 2026-06-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_portfolio_cash_aware_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='cash_aware_enabled',
            field=models.BooleanField(default=False, help_text='When true, cash-aware BUY/SELL settlements apply. DB default false preserves existing rows; new portfolios are created with true via application services unless explicitly false.'),
        ),
    ]
